name = "Synixe Contractors"
prefix = "synixe_contractors"
author = "Synixe Contractors"
files = [
    "mod.cpp",
    "logo_synixe_ca.paa",
    "meta.cpp"
]

modname = "synixe_contractors"
key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}"

check = [
    "!binarizer_link"
]
releasebuild = [
    "@zip SynixeContractors{{version}}"
]

[header_exts]
version = "{{git \"id 8\"}}"

# Binarizer file search compatibility
[scripts.binarizer_link]
steps_windows = [
    "if not exist x\\synixe_contractors mkdir x\\synixe_contractors",
    "if not exist x\\synixe_contractors\\addons mklink /j x\\synixe_contractors\\addons addons",
    "if not exist a3 mklink /j a3 include\\a3"
]
show_output = true
